sudo: false
language: php
services:
  - mysql
  - pgsql
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 6
  - 7
  - hhvm
env:
  - COMPOSER_ROOT_VERSION=dev-master
install:
  - composer install --prefer-dist
before_script:
  - sh -c "psql -c 'create database grocery;' -U postgres"
  - sh -c "mysql -e 'create database IF NOT EXISTS grocery;' -uroot"
script:
  - bin/spectre spec/**
