sudo: false
language: php
cache:
  directories:
  - $PWD/vendor
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
services:
  - mysql
  - pgsql
install:
  - COMPOSER_ROOT_VERSION=dev-master composer update --prefer-dist
before_script:
  - sh -c "psql -c 'create database grocery;' -U postgres"
  - sh -c "mysql -e 'create database IF NOT EXISTS grocery;' -uroot"
script:
  - bin/spectre spec
notifications:
  email: false
