sudo: false
language: php
env:
  - DB=mysql
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
env:
  - COMPOSER_ROOT_VERSION=dev-master
install:
  - composer install --prefer-dist
before_script:
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS grocery;'; fi"
script:
  - bin/spectre spec/**
